56 utilisation de la colonne normalized area pour les ratios c12c13 skyline
llegregam/MSReader pull request #61
Opened 2024-09-03 14:23 UTC by rkouakou06

J'ai modifié la méthode "generate_ratios" (j'ai mis en commentaire juste en dessous la précédente méthode). 

PS: il y a toujours les warning liés au "downcasting" : 
```
FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.data["Area"] = self.data["Area"].replace("N/F", 0).infer_objects(copy=False)
```
Pourtant j'ai ajouté infer_object(), du coup je capte pas trop

2024-09-03 14:33 UTC, llegregam requested changes
Juste changer le if else et logger les ratios ayant beugé et c'est bueno

2024-09-03 15:08 UTC, llegregam commented
J'ai eu un petit beug sur un fichier à moi ^^'
![image](https://github.com/user-attachments/assets/61e63eed-4688-4362-9dc8-4bf2f89fa52a)

2024-09-04 07:51 UTC, rkouakou06 commented
Tu as essayé avec cette version : 
pip install -U https://github.com/llegregam/MSReader/archive/refs/heads/56-utilisation-de-la-colonne-normalized-area-pour-les-ratios-c12c13-skyline.zip
?

2024-09-04 07:59 UTC, llegregam commented
Oui j'ai checkout la branche et j'ai installé la version en local

2024-09-09 14:22 UTC, merged